version: 0.0
os: linux
files:
   - source: /
     destination: /home/ip-172-31-47-108/apps/test100
permissions:
   - object: /home/ip-172-31-47-108/apps/test100
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/installapache.sh
      runas: root
    - location: scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: scripts/restartapache.sh
    - location: scripts/startApp.sh
      runas: root
